
DELETE http://localhost:3001/api/persons/3 HTTP/1.1


###
GET http://localhost:3001/api/persons/5 HTTP/1.1

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name" : "Silas Peters",
    "number" : "203-417-952"
}
