
DELETE http://localhost:3001/api/persons/63d0a90580d3712febaf59f2 HTTP/1.1


###
GET http://localhost:3001/api/persons/63d0a90580d3712febaf59f2 HTTP/1.1

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name" : "Odo Peter",
    "number" : "940-419-361"
}

###
PUT http://localhost:3001/api/persons/63d0ae7c1840b6fbaac0d612 HTTP/1.1
content-type: application/json

{
    "name": "Favor Ramon",
    "number": "080-345-433"
}