
DELETE http://localhost:3001/api/persons/63d0a90580d3712febaf59f2 HTTP/1.1


###
GET http://localhost:3001/api/persons/63d0a90580d3712febaf59f2 HTTP/1.1

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name" : "Brian Peters",
    "number" : "942-41328"
}

###
PUT http://localhost:3001/api/persons/63d1e32501f0d7f3e96ffacc HTTP/1.1
content-type: application/json

{
    "name": "Fav",
    "number": "080-345-433"
}